from enmapboxprocessing.algorithm.spectralresampling import SpectralSensors
from enmapboxprocessing.algorithm.spectralresamplingtosensoralgorithmbase import SpectralResamplingToSensorAlgorithmBase


class SpectralResamplingToEmitAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Emit
