from enmapboxprocessing.algorithm.spectralresampling import SpectralSensors
from enmapboxprocessing.algorithm.spectralresamplingtosensoralgorithmbase import SpectralResamplingToSensorAlgorithmBase


class SpectralResamplingToPrismaAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Prisma
