from enmapboxprocessing.algorithm.spectralresampling import SpectralSensors
from enmapboxprocessing.algorithm.spectralresamplingtosensoralgorithmbase import SpectralResamplingToSensorAlgorithmBase


class SpectralResamplingToSentinel2aAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Sentinel2a


class SpectralResamplingToSentinel2bAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Sentinel2b
