from enmapboxprocessing.algorithm.spectralresampling import SpectralSensors
from enmapboxprocessing.algorithm.spectralresamplingtosensoralgorithmbase import SpectralResamplingToSensorAlgorithmBase


class SpectralResamplingToEnmapAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Enmap
