from enmapboxprocessing.algorithm.spectralresampling import SpectralSensors
from enmapboxprocessing.algorithm.spectralresamplingtosensoralgorithmbase import SpectralResamplingToSensorAlgorithmBase


class SpectralResamplingToDesisAlgorithm(SpectralResamplingToSensorAlgorithmBase):
    sensor = SpectralSensors.Desis
