# run: conda env create --file conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: qgis
channels:
  - conda-forge
dependencies:
  - qgis>=3.26
  - pip
  - numpy
  - scipy
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - matplotlib
  - astropy
  - numba>=0.56.4
  - sympy
  - pyopengl
  - netcdf4
  - h5py
  - gitpython
  - git-lfs
  - sphinx
  - recommonmark
  - sphinx-rtd-theme
  - pip:
    - enpt-enmapboxapp
variables:
  QT_MAC_WANTS_LAYER: 1