# run: conda env create --file conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: enmapbox_light
channels:
  - conda-forge
dependencies:
  - qgis>=3.26
  - pip
variables:
  QT_MAC_WANTS_LAYER: 1