# run: conda env create --file conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: enmapbox_full
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - qgis>=3.28.2
  - pip  # avoids that conda uses the wrong pip
  - enpt

  # Polymer AC additional conda requirements
  - cdsapi
  - cython
  - gdal
  - netcdf4
  - pygrib
  - pyhdf
  - xarray

  # EnMAP-Box
  - astropy
  - catboost
  - lightgbm
  - matplotlib
  - numba>=0.56.4
  - numpy
  - qgis>=3.28.2
  - scikit-learn>=0.24
  - scipy>=1.1
  - typeguard
  - xgboost
  - sympy
  - pyopengl
  - h5py
  - gitpython
  - git-lfs
  - pip:
    # Polymer AC additional pip requirements
    - acwater>=0.3.0
    - enpt-enmapboxapp
variables:
  QT_MAC_WANTS_LAYER: 1