[enmapbox:metadata]
name = EnMAP-Box 3
version = 3.17.7
qgisMinimumVersion = 3.40
qgisMaximumVersion = 3.99
description = Imaging Spectroscopy and Remote Sensing for QGIS
tags =
    raster
    analysis
    imaging spectroscopy
    spectral
    hyperspectral
    multispectral
    landsat
    sentinel
    enmap
    desis
    prisma
    emit
    land cover
    landscape
    classification
    regression
    unmixing
    remote sensing
    mask
    accuracy
    clip
    spectral signature
    supervised classification
    clustering
    machine learning
    google earth engine
category = Analysis
authors =
    Andreas Janz
    Benjamin Jakimow
    Sebastian van der Linden
    Fabian Thiel
    Henrike Dierkes
icon = icon.png
homepage = https://enmap-box.readthedocs.io/
email = enmapbox@enmap.org
about = The EnMAP-Box is a QGIS plug-in to visualize and process remote sensing data. It has been
        particularly developed to handle data and products from imaging spectrometers, like EnMAP, PRISMA,
        EMIT, DESIS, Tanager, and multispectral instruments like Landsat and Sentinel-2.

        Publication:
        Jakimow, Janz, Thiel, Okujeni, Hostert, van der Linden, 2023: EnMAP-Box: Imaging spectroscopy in QGIS.
        SoftwareX 23, 101507, https://doi.org/https://doi.org/10.1016/j.softx.2023.101507

        Links:
        - Documentation: https://enmap-box.readthedocs.io
        - Code: https://github.com/EnMAP-Box/enmap-box
        - Environmental Mapping and Analysis Program (EnMAP): https://www.enmap.org
        - License: GNU GPL-3 https://www.gnu.org/licenses/gpl-3.0

        Acknowledgements:

        The EnMAP-Box is developed at Humboldt-Universität zu Berlin under contract by the GFZ Helmholtz Centre
        for Geosciences and is part of the EnMAP Core Science Team activities.
        It is funded by the German Aerospace Centre (DLR) - Project Management Agency,
        granted by the Federal Ministry of Research, Technology and Space (https://www.bmbf.de, BMFTR; grant no. 50EE2401A).


[enmapbox:plugin]
# maximum plugin size in MBytes
max_size_mb = 10

[enmapbox:files]
# the icon source that will be used for the [metadata] icon
icon = enmapbox/gui/ui/icons/enmapbox64px.png

# file patterns can be defined by :
# no prefix  -> glob / fnmatch pattern
# prefix rx: -> regular expression
ignore =
    *.pyc
# ignore hidden files and folders like .gitignore
# rx:.*/\..*
    rx:^\.(?!/env).*

include =
    .env/*
# include all apps except submodule folders
    rx:enmapbox/apps/(?!lmuapps).*
# include apps that are submodules
    rx:enmapbox/apps/lmuapps/lmuvegetationapps/.*
    enmapbox/coreapps/*
    enmapbox/eo4qapps/*
    enmapbox/typeguard/*
    enmapbox/provider/*
    rx:enmapbox/gui/.*\.(py|ui)
    rx:enmapbox/[^/]+\.(py|txt)

# deprecated!
    enmapbox/gui/externals/*
# single files but not subfolders
# rx:enmapbox/[^/]\.*
    site-packages/*
# enmapboxprocessing/*
    rx:enmapboxprocessing/.*\.(py|ui|txt|json|csv|csvt|geojson|qml)
    rx:enmapboxexternal/.*\.(py)
    enmapboxplugins/*
    enmapboxgeoalgorithms/*
    enmapbox/gui/splashscreen/splashscreen.png
    enmapbox/gui/ui/logo/logo_enmapbox.png
    __init__.py
    CHANGELOG.rst
    CHANGELOG.md
    CONTRIBUTORS.md
    CREDITS.md
    ABOUT.md
    LICENSE.md
    LICENSE.txt
    requirements.txt
    requirements_developer.txt
    enmapboxprocessing/glossary.rst

exclude =
    enmapbox/exampledata/*
    rx:.*symbology-style.db


[coveragec:run]
include =
    enmapbox/*
    enmapboxprocessing/*

# omit =



[flake8]
# see https://flake8.pycqa.org/en/latest/user/configuration.html
ignore =
#
# allow complex functions
    C901,
#    D203,
# continuation line missing indentation or outdented
#    E122,
#    E126,
# allow continuation line over-indented for hanging indent
#    E501,
# allow lambda functions
#    E731,
# allow ambiguous variable names
#    E741,
# allow unused local variables
#    F821,
# undefined name
#    F841,
# allow to annotate not used variables
#    F842,
# Do not pass iface (QgisInterface) as an argument, instead import it: 'from qgis.utils import iface'
#    QGS105,QGS110,
# QGS201 (experimental) Check the success flag and possibly error message from return value of QgsProject.addMapLayers().
# QGS202 (experimental) Check the success flag and possibly error message from return value of the method if it is QgsCodeEditorWidget.loadFile(). Otherwise ignore
    QGS201, QGS202,
# Use 'exec' instead of 'exec_'
#    QGS111,QGS107,
#    QGS402,QGS403,QGS404,QGS407,QGS412,

# allow line break before binary operator
    W503


max-line-length = 120
max-complexity = 10

exclude =
    .git,
    __pycache__,
    deploy
    test-reports,
    test-outputs,
    qgisresources


# per-file-ignores =


[pytest]
env =
    PYQTGRAPH_QT_LIB=PyQt5
# CI=False
# QT_QPA_PLATFORM=offscreen

pythonpath =
    enmapbox/apps
    enmapbox/coreapps
    enmapbox/eo4qapps
    tests/src

addopts =
    --maxfail=1000
    --ignore=tests/_wip/
    --cov-config=.coveragec
    --ignore=tests/enmap-box/enmapbox/apps/otherapps/test_ensomap.py
filterwarnings =
    ignore::UserWarning
    ignore::RuntimeWarning
    ignore::DeprecationWarning

norecursedirs =
    .*
    qpstestdata
    scripts
    qgisresources
    tmp
    test-outputs
    *.egg
    venv
# tests/enmap-box/enmapbox/apps
# tests/enmap-box/enmapbox/apps/SpecDeepMap
# tests/enmap-box/enmapbox/coreapps
# tests/enmap-box/enmapbox/coreapps
# tests/enmap-box/enmapbox/apps/SpecDeepMap
    tests/excluded
# tests/enmap-box/enmapbox/apps/otherapps/test_enpt_enmapboxapp.py
# tests/enmap-box/enmapbox/eo4qapps
# tests/enmap-box/enmapbox/gui
# tests/enmap-box/enmapbox/provider

python_files =
    test_*.py
# tests/src/core/test_applications.py
# tests/src/otherapps/test_enpt_enmapboxapp.py
# tests/src/otherapps/test_ensomap.py
# tests/src/otherapps/test_lmuvegetationapps.py
# tests/enmap-box/enmapboxprocessing/algorithm/test_ClassificationPerformanceSimpleAlgorithm.py
# tests/enmap-box/enmapboxprocessing/algorithm/test_ClassificationWorkflowAlgorithm.py

testpaths =
# NOTE: remove all (!) `#` characters from uncommented lines
    tests/
# tests/fatal_crashes/test_segfault.py
# tests/src/core
