services:

  qgis:
    build:
      context: ../..
      dockerfile: .env/docker/Dockerfile
      args:
        QGIS_VERSION: ${QGIS_VERSION:-latest}
    tty: true
    volumes:
      # - ${GITHUB_WORKSPACE}:/usr/src
      - ${GITHUB_WORKSPACE:-.}:/usr/src
