version: '3'
services:

  qgis:
    build:
      context: .env/docker/
      dockerfile: Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
      #- ${PWD}/:/usr/src
