
:: use this script to run unit tests locally
::
@echo off
set CI=True
set PYTHONPATH=%~dp0/..;%PYTHONPATH%
set PYTHONPATH
set PYTHON=python
::WHERE python3 >nul 2>&1 && (
::    echo Found "python3" command
::    set PYTHON=python3
::) || (
::    echo Did not found "python3" command. use "python" instead
::    set PYTHON=python
::)

::start %PYTHON% scripts/setup_repository.py

%PYTHON% -m coverage run --rcfile=.coveragec   tests/src/core/test_applications.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_crosshair.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_cursorlocationsvalues.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_datasources.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_dependencycheck.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_enmapbox.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_enmapboxplugin.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_enmapboxprocessingprovider.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_enmapbox_utils.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_mapcanvas.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_mimedata.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_processing_framework.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_settings.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_speclibs.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_spectral_processing.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_splashscreen.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_testing.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_utils.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/core/test_vectorlayertools.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/coreapps/test_enmapboxapplications.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/coreapps/test_imagecube.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/coreapps/test_metadataeditorapp.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/coreapps/test_reclassifyapp.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/coreapps/test_vrtbuilderapp.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/enmapboxplugins_/test_classfractionrenderer.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/enmapboxplugins_/test_decorrelationstretchrenderer.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_1089.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_1330_QGIS.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_1386.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_478.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_711.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_724.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/issues/test_issue_737.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/otherapps/test_enpt_enmapboxapp.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/otherapps/test_ensomap.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/otherapps/test_lmuvegetationapps.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/test_docksanddatasources.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/test_repo.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/test_template.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/widgets_/test_CodeEditWidget.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  tests/src/widgets_/test_MultipleMapLayerSelectionWidget.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_AggregateRasterBandsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ApplyMaskAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassFractionFromCategorizedVectorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassificationFromClassProbabilityAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassificationPerformanceSimpleAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassificationPerformanceStratifiedAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassificationWorkflowAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassifierPerformanceAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ClassifierPermutationFeatureImportanceAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ConvexHullAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ConvolutionFilterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_CreateDefaultPalettedRasterRendererAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_CreateGridAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_CreateMaskAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_CreateRgbImageFromClassProbabilityAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_CreateSpectralIndicesAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_EditRasterSourceBandPropertiesAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_FeatureClusteringHierarchicalAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_FitClassifierAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_FitClustererAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_FitRegressorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_FitTransformerAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_GeolocateRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportDesisL1BAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportDesisL1CAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportDesisL2AAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportEnmapL1BAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportEnmapL1CAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportEnmapL2AAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportLandsatL2Algorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportPrismaL1Algorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportPrismaL2BAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportPrismaL2CAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportPrismaL2DAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_ImportSentinel2L2AAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_LayerToMaskAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_MergeClassificationDatasetAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PredictClassificationAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PredictClassProbabilityAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PredictRegressionAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromCategorizedLibraryAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromCategorizedRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromCategorizedVectorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromCategorizedVectorAndFieldsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromCodeAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromFilesAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareClassificationDatasetFromTableAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromCodeAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromContinuousLibraryAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromContinuousRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromContinuousVectorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromContinuousVectorAndFieldsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromFilesAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromSynthMixAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareRegressionDatasetFromTableAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareUnsupervisedDatasetFromCodeAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareUnsupervisedDatasetFromFileAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareUnsupervisedDatasetFromLibraryAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareUnsupervisedDatasetFromRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_PrepareUnsupervisedDatasetFromVectorAndFieldsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RandomPointsInMaskAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RandomPointsInStratificationAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RandomSamplesFromClassificationDatasetAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RandomSamplesFromRegressionDatasetAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RasterizeCategorizedVectorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RasterizeVectorAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RasterLayerZonalAggregationAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RasterMathAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RegeressionPerformanceAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RegressionBasedUnmixingAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RegressionWorkflowAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RegressorPerformanceAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_RocCurveAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SampleRasterValuesAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SaveLibraryAsGeoJsonAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SaveRasterAsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SelectFeaturesFromDatasetAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SpatialFilterFunctionAlgorithmBase.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SpectralResamplingByResponseFunctionConvolutionAlgorithmBase.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SpectralResamplingByResponseFunctionLibraryAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SpectralResamplingBySpectralRasterWavelengthAndFwhmAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_StackRasterLayersAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_SubsetRasterBandsAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_TransformRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_TranslateClassificationAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_TranslateRasterAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_VrtBandMathAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/algorithm/test_WriteEnviHeaderAlgorithm.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_extentwalker.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_glossary.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_gridwalker.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_guidropping.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_numpyutils.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterdriver.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rastermetadataeditor.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterprocessing.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterreader.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterreaderrfc1.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterreaderrfc2.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterreaderrfc3.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_rasterreaderrfc4.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_reportwriter.py
%PYTHON% -m coverage run --rcfile=.coveragec --append  enmapboxprocessing/test/test_utils.py
%PYTHON% -m coverage report