import argparse
import pathlib
import re
import site

DIR_REPO = pathlib.Path(__file__).parents[1]
DIR_TESTS = DIR_REPO / 'tests'
DIR_UNITTESTDATA = DIR_TESTS / 'testdata'
PATH_TEST_INIT = DIR_UNITTESTDATA / '__init__.py'
assert DIR_UNITTESTDATA.is_dir()


def update_unittest_init(
        use_pathlib: bool = True,
        overwrite: bool = False):
    site.addsitedir(pathlib.Path(__file__).parents[1])
    from enmapbox.gui.utils import file_search

    if not overwrite and PATH_TEST_INIT.is_file():
        raise Exception(f'File already exists: {PATH_TEST_INIT}.\nRun with option -o --overwrite')

    rx = re.compile(r'.*\.(tif|gpkg|qml|csv|pkl|json)$')

    FILES = dict()
    for file in file_search(DIR_UNITTESTDATA, rx, recursive=True):
        path = pathlib.Path(file)
        part = path.relative_to(DIR_UNITTESTDATA).as_posix()
        varname = re.sub(r'[/\-*?.]', '_', part)
        part = "' / '".join(part.split('/'))

        if use_pathlib:
            FILES[path] = f"{varname} = root / '{part}'"
        else:
            FILES[path] = f"{varname} = (root / '{part}').as_posix()"

    lines = ['# autogenerated file. ',
             '# changes will be overwritten when running {pathlib.Path(__file__).relative_to(DIR_REPO)}',
             'import pathlib',
             'root = pathlib.Path(__file__).parent',
             '']
    for file in FILES.values():

        lines.append(file)

    with open(PATH_TEST_INIT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    site.addsitedir(PATH_TEST_INIT.parents[1])
    from testdata import root
    assert isinstance(root, pathlib.Path)
    assert root.is_dir()


if __name__ == "__main__":
    part = PATH_TEST_INIT.relative_to(DIR_REPO)
    parser = argparse.ArgumentParser(description=f'Updates path variable in {part}')
    parser.add_argument('-o', '--overwrite',
                        required=False,
                        default=True,
                        help='Overwrite existing __init__.py',
                        action='store_true')
    parser.add_argument('-p', '--pathlib',
                        required=False,
                        default=False,
                        help='Makes file paths available as pathlib.Path',
                        action='store_true')

    args = parser.parse_args()

    update_unittest_init(use_pathlib=args.pathlib, overwrite=args.overwrite)
