name: 🐍 EnMAP-Box Mamba Tests

on:
  push:
    branches:
      - main
      - release-**

  pull_request:
    branches:
      - main
      - release-**

  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mamba_env: [enmapbox_light_latest, enmapbox_light_longterm]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Create & activate mamba environment
        run: | 
          mamba env create -f .conda/${{matrix.mamba_env}}.yml
          mamba activate ${{matrix.mamba_env}}

      - name: Python Packages Info
        run: |
          python3 --version
          pip list
          qgis --version
