name: 🧪 EnMAP-Box Tests

on:
  push:
    branches:
      #- main
      #- release-**
      - 14-setup-gh-actions**

  pull_request:
    branches:
      - main
      - release-**
  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test on QGIS
        run: |
          ls -la .docker/
          ls -la
          chmod +x .docker/run_docker_tests.sh
          pwd
          docker -h
          sudo docker-compose version
        # docker-compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run_docker_tests.sh
