name: 🧪 EnMAP-Box Tests

on:
  push:
    branches:
      - main
      - release-**
      - refactor_environments

  pull_request:
    branches:
      - main
      - release-**

  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qgis_version: [release-3_28, release-3_32]
      fail-fast: false

    env:
        QGIS_TEST_VERSION: ${{ matrix.qgis_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker Environment Info
        run: |
          # ls -la .env/docker/
          # ls -la
          # ls -la ~
          # ls -la /usr/bin
          docker --version
      - name: Python Packages Info
        run: |
          python3 --version
          pip list
      - name: Test EnMAP-Box on QGIS
        run: | 
          chmod +x .env/docker/run_docker_tests.sh
          ls -la .env/docker/
          docker compose -f .env/docker/docker-compose.gh.yml run qgis /usr/src/.env/docker/run_docker_tests.sh
