name: 🧪 EnMAP-Box Tests

on:
  push:
    branches:
      #- main
      #- release-**
      - 14-setup-gh-actions**

  pull_request:
    branches:
      - main
      - release-**
  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [latest]
    env:
        QGIS_TEST_VERSION: ${{ matrix.qgis_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Environment Info
        run: |
          # ls -la .docker/
          # ls -la
          ls -la ~
          
          ls -la /usr/bin
          # chmod +x .docker/run_docker_tests.sh
          
          # docker -h
      - name: Test EnMAP-Box on QGIS
        run: docker-compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run_docker_tests.sh
