name: 🐍 EnMAP-Box Mamba Tests

on:
  push:
    branches:
      - mamba**

  pull_request:
    branches:
      - main
      - release-**

  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        mamba_env: [enmapbox_light_latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Inspect conda environment file
        run: |
          ls -lisa .conda
          cat .conda/${{matrix.mamba_env}}.yml

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ${{matrix.mamba_env}}
          environment-file: .conda/${{matrix.mamba_env}}.yml
          use-mamba: true
          auto-activate-base: false
      - name: Mamba Environment Info
        run: |
          mamba info
          mamba list
      - name: Python Packages Info
        run: |
          qgis --version
