name: 🧪 EnMAP-Box Tests

on:
  push:
    branches:
      - main
      - release-**
      - release_**

  pull_request:
    branches:
      - main
      - release-**
      - release_**

  release:
    types: [ published ]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qgis_version: [ '3.34', '3.38', '3.40' ]
      fail-fast: true

    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker Environment Info
        run: |
          # ls -la .docker/
          # ls -la
          # ls -la ~
          # ls -la /usr/bin
          docker --version
          lsb_release -a
      - name: Python Packages Info
        run: |
          python3 --version
          pip list
      - name: Test EnMAP-Box on QGIS
        run: |
          chmod +x .env/docker/run_docker_tests.sh
          ls -la .env/docker
          docker compose -f .env/docker/docker-compose.gh.yml run qgis /usr/src/.env/docker/run_docker_tests.sh -n auto
