name: 🐍 EnMAP-Box Mamba Tests

on:
  push:
    branches:
      - mamba**

  pull_request:
    branches:
      - main
      - release-**

  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mamba_env: [enmapbox_light_latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Inspect Files
        run: |
          ls -lisa
          ls -lisa ./conda

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: .conda/${{matrix.mamba_env}}
          use-mamba: true

      - name: Python Packages Info
        run: |
          python3 --version
          pip list
          qgis --version
