name: 🐍 Conda Environments

on:
  push:
    branches:
      - main
      - release-**
      - release_**

  pull_request:
    branches:
      - main
      - release-**
      - release_**

  release:
    types: [ published ]

jobs:
  # Run EnMAP-Box tests
  test:
    name: ${{ matrix.mamba_env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    env:
      QT_QPA_PLATFORM: offscreen
      CI: true

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        mamba_env: [ enmapbox-base ]
        include:
          - os: windows-latest
            qgis_python_path: $CONDA_PREFIX\Library\python
            qgis_bin_path: $CONDA_PREFIX\Library\bin
          - os: ubuntu-latest
            qgis_python_path: ""
            qgis_bin_path: ""
          - os: macos-latest
            qgis_python_path: ""
            qgis_bin_path: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Runner Info
        run: |
          uname -a || true
          echo "OS: ${{ runner.os }}"

      - name: Conda environment file
        run: |
          echo "conda environment file: .env/conda/${{ matrix.mamba_env }}.yml"
          cat .env/conda/${{ matrix.mamba_env }}.yml

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: ${{ matrix.mamba_env }}
          environment-file: .env/conda/${{ matrix.mamba_env }}.yml
          clean-patched-environment-file: false

      - name: Conda Environment Info
        run: |
          conda info
          conda list

      - name: Python, QGIS and GDAL versions
        run: |
          if [ -n "${{ matrix.qgis_python_path }}" ]; then
            export PYTHONPATH="${{ matrix.qgis_python_path }}:$PYTHONPATH"
          fi
          if [ -n "${{ matrix.qgis_bin_path }}" ]; then
            export PATH="${{ matrix.qgis_bin_path }}:$PATH"
          fi
          python --version
          qgis --version || true
          gdalinfo --version || true
          python -c "from osgeo.gdal import VersionInfo; print(f\"Python-GDAL: {VersionInfo('')} {VersionInfo()}\")"
          python -c "from qgis.core import Qgis; print(f\"Python-QGIS: {Qgis.version()} \")"

      - name: Setup Repository
        run: |
          if [ -n "${{ matrix.qgis_python_path }}" ]; then
            export PYTHONPATH="${{ matrix.qgis_python_path }}:$PYTHONPATH"
          fi
          if [ -n "${{ matrix.qgis_bin_path }}" ]; then
            export PATH="${{ matrix.qgis_bin_path }}:$PATH"
          fi
          python scripts/setup_repository.py

      - name: Test EnMAP-Box in ${{ matrix.mamba_env }}
        run: |
          if [ -n "${{ matrix.qgis_python_path }}" ]; then
            export PYTHONPATH="${{ matrix.qgis_python_path }}:$PYTHONPATH"
          fi
          if [ -n "${{ matrix.qgis_bin_path }}" ]; then
            export PATH="${{ matrix.qgis_bin_path }}:$PATH"
          fi
          chmod +x scripts/runtests.sh
          bash ./scripts/runtests.sh -x -n 1 --maxfail=2
