name: 🧪 EnMAP-Box Tests

on:
  push:
    branches:
      - main
      - release-**

  pull_request:
    branches:
      - main
      - release-**
  release:
    types: [published]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [release-3_28, release-3_30, latest]
        python: [3.10]
    env:
        QGIS_TEST_VERSION: ${{ matrix.qgis_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker Environment Info
        run: |
          # ls -la .docker/
          # ls -la
          # ls -la ~
          # ls -la /usr/bin
          docker --version
      - name: Python Packages Info
        run: pip list
      - name: Test EnMAP-Box on QGIS
        run: | 
          chmod +x .docker/run_docker_tests.sh
          ls -la .docker/
          docker compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run_docker_tests.sh
