name: SpecDeepMap Tests

on:
  push:
    branches:
      - main
      - release-**
      - release_**

  pull_request:
    branches:
      - main
      - release-**
      - release_**

  release:
    types: [ published ]

jobs:
  # Run EnMAP-Box tests
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    env:
      QT_QPA_PLATFORM: offscreen
      CI: true

    strategy:
      fail-fast: true
      matrix:
        mamba_env: [ ".env/conda/enmapbox-full.yml" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Runner Info
        run: |
          uname -a || true
          echo "OS: ${{ runner.os }}"

      - name: Conda environment file
        run: |
          echo "conda environment file: .env/conda/${{ matrix.mamba_env }}.yml"
          cat .env/conda/${{ matrix.mamba_env }}.yml

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: ${{ matrix.mamba_env }}
          environment-file: .env/conda/${{ matrix.mamba_env }}.yml
          clean-patched-environment-file: false

      - name: Conda Environment Info
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Setup Repository
        run: |
          python scripts/setup_repository.py

      - name: Test SpecDeepMap in ${{matrix.mamba_env}}
        run: |
          pwd
          ls -la
          python3 -m unittest discover -s tests/enmap-box/enmapbox/apps/SpecDeepMap -t tests/enmap-box/enmapbox/apps/SpecDeepMap
