name: Check URLs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: urls-checker
      uses: urlstechie/urlchecker-action@master
      with:
        file_types: .md,.py,.rst

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        timeout: 5

        retry_count: 3

        verbose: true

        force_pass : false

        # {z}/{x}/{y}: CartoDB, ESRI, Open Weather, OSM, Stamen, Strava, Wikimedia
        # x={x}&y={y}&z={z}: Google
        exclude_patterns:
          http://ecn.t3.tiles.virtualearth.net/,http://fbinter.stadt-berlin.de/,http://tiles.wmflabs.org/
